// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbqjukdkqzlcmkqfiaxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icWp1a2RrcXpsY21rcWZpYXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjUyMjAsImV4cCI6MjA2MDY0MTIyMH0.svl90yVSdSlb8wbD-AUL9t0klfd1v16RLgFDh4KOBOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);